default:
  resolution: 0.05
  width: 600       # 30 meters
  height: 600      # 30 meters
  origin_x: -15.0
  origin_y: -15.0
  l_occ: 0.85
  l_free: -0.4
  navigable_area: 900.0 # Total grid area as fallback

SLAM_Project:
  resolution: 0.05
  width: 300       # 15 meters
  height: 300      # 15 meters
  origin_x: -7.5
  origin_y: -7.5
  navigable_area: 20.0 # Estimated 20m^2 for the small room
